export const ArbitrationSystemABI = [
  {
    inputs: [{ internalType: 'address', name: '_escrowContract', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'disputeId', type: 'uint256' },
      { indexed: false, internalType: 'address[]', name: 'arbitrators', type: 'address[]' },
    ],
    name: 'ArbitratorsAssigned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'refundedAmount', type: 'uint256' },
    ],
    name: 'ArbitratorDeactivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'ArbitratorPenalized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'stakedAmount', type: 'uint256' },
    ],
    name: 'ArbitratorRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'ArbitratorRewarded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'disputeId', type: 'uint256' },
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
    ],
    name: 'DisputeCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'disputeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'winner', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'buyerVotes', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'sellerVotes', type: 'uint256' },
    ],
    name: 'DisputeResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'disputeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'submitter', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'isBuyer', type: 'bool' },
    ],
    name: 'EvidenceSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'newTotal', type: 'uint256' },
    ],
    name: 'StakeIncreased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'disputeId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'arbitrator', type: 'address' },
      { indexed: false, internalType: 'enum ArbitrationSystem.Vote', name: 'vote', type: 'uint8' },
    ],
    name: 'VoteCast',
    type: 'event',
  },
  {
    inputs: [],
    name: 'ARBITRATORS_PER_DISPUTE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_STAKE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'QUORUM_SIZE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'VOTING_PERIOD',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'arbitratorList',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'arbitrators',
    outputs: [
      { internalType: 'address', name: 'arbitratorAddress', type: 'address' },
      { internalType: 'uint256', name: 'stakedAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'totalCasesAssigned', type: 'uint256' },
      { internalType: 'uint256', name: 'totalCasesVoted', type: 'uint256' },
      { internalType: 'uint256', name: 'correctVotes', type: 'uint256' },
      { internalType: 'uint256', name: 'reputation', type: 'uint256' },
      { internalType: 'bool', name: 'isActive', type: 'bool' },
      { internalType: 'uint256', name: 'registeredAt', type: 'uint256' },
      { internalType: 'uint256', name: 'lastActiveAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_disputeId', type: 'uint256' },
      { internalType: 'enum ArbitrationSystem.Vote', name: '_vote', type: 'uint8' },
    ],
    name: 'castVote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_transactionId', type: 'uint256' },
      { internalType: 'address', name: '_buyer', type: 'address' },
      { internalType: 'address', name: '_seller', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'createDispute',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deactivateArbitrator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'disputeCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'disputes',
    outputs: [
      { internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { internalType: 'address', name: 'buyer', type: 'address' },
      { internalType: 'address', name: 'seller', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'string', name: 'buyerEvidence', type: 'string' },
      { internalType: 'string', name: 'sellerEvidence', type: 'string' },
      { internalType: 'enum ArbitrationSystem.DisputeStatus', name: 'status', type: 'uint8' },
      { internalType: 'uint256', name: 'buyerVotes', type: 'uint256' },
      { internalType: 'uint256', name: 'sellerVotes', type: 'uint256' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'uint256', name: 'votingDeadline', type: 'uint256' },
      { internalType: 'address', name: 'winner', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'escrowContract',
    outputs: [{ internalType: 'contract IBaseEscrow', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_disputeId', type: 'uint256' }],
    name: 'finalizeDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActiveArbitratorsCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_arbitrator', type: 'address' }],
    name: 'getArbitrator',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'arbitratorAddress', type: 'address' },
          { internalType: 'uint256', name: 'stakedAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'totalCasesAssigned', type: 'uint256' },
          { internalType: 'uint256', name: 'totalCasesVoted', type: 'uint256' },
          { internalType: 'uint256', name: 'correctVotes', type: 'uint256' },
          { internalType: 'uint256', name: 'reputation', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
          { internalType: 'uint256', name: 'registeredAt', type: 'uint256' },
          { internalType: 'uint256', name: 'lastActiveAt', type: 'uint256' },
        ],
        internalType: 'struct ArbitrationSystem.Arbitrator',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_arbitrator', type: 'address' }],
    name: 'getArbitratorDisputes',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_disputeId', type: 'uint256' },
      { internalType: 'address', name: '_arbitrator', type: 'address' },
    ],
    name: 'getArbitratorVote',
    outputs: [{ internalType: 'enum ArbitrationSystem.Vote', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_disputeId', type: 'uint256' }],
    name: 'getDispute',
    outputs: [
      { internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { internalType: 'address', name: 'buyer', type: 'address' },
      { internalType: 'address', name: 'seller', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'string', name: 'buyerEvidence', type: 'string' },
      { internalType: 'string', name: 'sellerEvidence', type: 'string' },
      { internalType: 'enum ArbitrationSystem.DisputeStatus', name: 'status', type: 'uint8' },
      { internalType: 'uint256', name: 'buyerVotes', type: 'uint256' },
      { internalType: 'uint256', name: 'sellerVotes', type: 'uint256' },
      { internalType: 'uint256', name: 'votingDeadline', type: 'uint256' },
      { internalType: 'address', name: 'winner', type: 'address' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_disputeId', type: 'uint256' }],
    name: 'getDisputeArbitrators',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'increaseStake',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_disputeId', type: 'uint256' },
      { internalType: 'address', name: '_arbitrator', type: 'address' },
    ],
    name: 'isAssignedArbitrator',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registerArbitrator',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_disputeId', type: 'uint256' },
      { internalType: 'string', name: '_evidence', type: 'string' },
    ],
    name: 'submitEvidence',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalArbitrators',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'transactionToDispute',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
