export const BaseEscrowABI = [
  {
    inputs: [{ internalType: 'uint256', name: '_protocolFeePercentage', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'initiator', type: 'address' },
      { indexed: false, internalType: 'string', name: 'reason', type: 'string' },
    ],
    name: 'DisputeInitiated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'winner', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'DisputeResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'FundsReleased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'rater', type: 'address' },
      { indexed: true, internalType: 'address', name: 'rated', type: 'address' },
      { indexed: false, internalType: 'uint8', name: 'score', type: 'uint8' },
    ],
    name: 'RatingSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'ReceiptConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'RefundIssued',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'ShipmentConfirmed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'claimer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'TimeoutClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'canceller', type: 'address' },
    ],
    name: 'TransactionCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'enum BaseEscrow.Category', name: 'category', type: 'uint8' },
      { indexed: false, internalType: 'string', name: 'description', type: 'string' },
    ],
    name: 'TransactionCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'transactionId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'buyer', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
    ],
    name: 'TransactionFunded',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
    name: 'calculateProtocolFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'cancelTransaction',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'claimAfterBuyerTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'claimAfterSellerTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'confirmReceipt',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'confirmShipment',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address payable', name: '_seller', type: 'address' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'enum BaseEscrow.Category', name: '_category', type: 'uint8' },
    ],
    name: 'createTransaction',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getAverageRating',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_transactionId', type: 'uint256' }],
    name: 'getTransaction',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address payable', name: 'buyer', type: 'address' },
          { internalType: 'address payable', name: 'seller', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'enum BaseEscrow.Category', name: 'category', type: 'uint8' },
          { internalType: 'enum BaseEscrow.TransactionStatus', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'fundedAt', type: 'uint256' },
          { internalType: 'uint256', name: 'shipmentConfirmedAt', type: 'uint256' },
          { internalType: 'uint256', name: 'completedAt', type: 'uint256' },
          { internalType: 'uint256', name: 'buyerTimeout', type: 'uint256' },
          { internalType: 'uint256', name: 'sellerTimeout', type: 'uint256' },
          { internalType: 'bool', name: 'buyerRated', type: 'bool' },
          { internalType: 'bool', name: 'sellerRated', type: 'bool' },
        ],
        internalType: 'struct BaseEscrow.Transaction',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserProfile',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'totalTransactionsAsBuyer', type: 'uint256' },
          { internalType: 'uint256', name: 'totalTransactionsAsSeller', type: 'uint256' },
          { internalType: 'uint256', name: 'completedTransactions', type: 'uint256' },
          { internalType: 'uint256', name: 'disputedTransactions', type: 'uint256' },
          { internalType: 'uint256', name: 'totalRatingsReceived', type: 'uint256' },
          { internalType: 'uint256', name: 'ratingSum', type: 'uint256' },
          { internalType: 'bool', name: 'exists', type: 'bool' },
        ],
        internalType: 'struct BaseEscrow.UserProfile',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserRatings',
    outputs: [
      {
        components: [
          { internalType: 'uint8', name: 'score', type: 'uint8' },
          { internalType: 'string', name: 'comment', type: 'string' },
          { internalType: 'uint256', name: 'timestamp', type: 'uint256' },
          { internalType: 'uint256', name: 'transactionId', type: 'uint256' },
        ],
        internalType: 'struct BaseEscrow.Rating[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
    name: 'getUserTransactions',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_transactionId', type: 'uint256' },
      { internalType: 'string', name: '_reason', type: 'string' },
    ],
    name: 'initiateDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'protocolFeePercentage',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_transactionId', type: 'uint256' },
      { internalType: 'address', name: '_winner', type: 'address' },
    ],
    name: 'resolveDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_transactionId', type: 'uint256' },
      { internalType: 'uint8', name: '_score', type: 'uint8' },
      { internalType: 'string', name: '_comment', type: 'string' },
    ],
    name: 'submitRating',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'transactionCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'transactions',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address payable', name: 'buyer', type: 'address' },
      { internalType: 'address payable', name: 'seller', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'protocolFee', type: 'uint256' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'enum BaseEscrow.Category', name: 'category', type: 'uint8' },
      { internalType: 'enum BaseEscrow.TransactionStatus', name: 'status', type: 'uint8' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'uint256', name: 'fundedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'shipmentConfirmedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'completedAt', type: 'uint256' },
      { internalType: 'uint256', name: 'buyerTimeout', type: 'uint256' },
      { internalType: 'uint256', name: 'sellerTimeout', type: 'uint256' },
      { internalType: 'bool', name: 'buyerRated', type: 'bool' },
      { internalType: 'bool', name: 'sellerRated', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
